server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/islittlechen/webintegration
          label: web-integration-dev
          username: islittlechen
          password: ilc227610
          search-paths: spring-cloud-config-project/