server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/islittlechen/git-config-repo.git
          label: master
          username: islittlechen@sina.cn
          password: ilc227610
          search-paths: api-integration-config,api-gateway-config,eureka-server-config,api-consumer-config
