server:
  port: 8889

spring:
  application:
    name: api-integration
  cloud:
    config:
      name: api-integration
      profile: dev
      uri: http://localhost:8888
      label: master

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    eureka-server-port: 1110
    service-url:
      defaultZone: http://localhost:1110/eureka/
