server:
  port: 8889

spring:
  application:
    name: api-integration
  cloud:
    config:
      name: api-integration
      profile: dev
      uri: http:localhost:8888/
      label: web-integration-dev

management:
  security:
    enabled: false